# Generated by Django 3.1.5 on 2021-03-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likeInfo',
        ),
    ]
