# Generated by Django 3.1.5 on 2021-03-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_comment_follow_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
